name: cleanpy
channels:
- conda-forge
- defaults
channel_priority: strict
dependencies:
- python=3.11
- pip
- setuptools
- wheel
- numpy
- scipy
- pandas
- xarray
- netcdf4
- cftime
- h5py
- zarr
- matplotlib
- seaborn
- statsmodels
- scikit-learn
- numba
- tqdm
- requests
- pyyaml
- ipykernel
- bottleneck
- hdf5
- joblib
- matplotlib-base
- numpy-base
- patsy
- R
- r-this.path
- r-abind
- python-dateutil
- python-tzdata
- python_abi
- pip:
  - attrs==25.3.0
  - fastjsonschema==2.21.1
  - gsw==3.6.19
  - jsonschema==4.24.0
  - jsonschema-specifications==2025.4.1
  - jupyter-core==5.8.1
  - nbformat==5.10.4
  - nbstripout==0.8.1
  - platformdirs==4.3.8
  - pytz==2025.2
  - referencing==0.36.2
  - rpds-py==0.26.0
  - traitlets==5.14.3
  - xarray==2025.3.1
  - mplcursors==0.7
