name: cleanpy
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex==4.5=3_kmp_llvm
  - alsa-lib=1.2.14=hb9d3cd8_0
  - blas=1.0=mkl
  - blosc=1.21.6=hef167b5_0
  - bottleneck=1.4.2=py313hf0014fa_0
  - brotli=1.1.0=hb9d3cd8_3
  - brotli-bin=1.1.0=hb9d3cd8_3
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.4=hb9d3cd8_0
  - ca-certificates=2025.2.25=h06a4308_0
  - cairo=1.18.4=h3394656_0
  - certifi=2025.4.26=py313h06a4308_0
  - cftime=1.6.4=py313hf0014fa_0
  - contourpy=1.3.2=py313h33d0bda_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.27=h54b06d7_7
  - dbus=1.16.2=h3c4dab8_0
  - double-conversion=3.3.1=h5888daf_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.58.4=py313h8060acc_0
  - freetype=2.13.3=ha770c72_1
  - graphite2=1.3.14=h5888daf_0
  - harfbuzz=11.2.1=h3beb420_0
  - hdf4=4.2.15=h2a13503_7
  - hdf5=1.14.3=nompi_h2d575fe_109
  - icu=75.1=he02047a_0
  - joblib=1.4.2=py313h06a4308_0
  - kiwisolver=1.4.8=py313h6a678d5_0
  - krb5=1.21.3=h143b758_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h0aef613_1
  - libaec=1.1.3=h6a678d5_0
  - libblas=3.9.0=26_linux64_mkl
  - libbrotlicommon=1.1.0=hb9d3cd8_3
  - libbrotlidec=1.1.0=hb9d3cd8_3
  - libbrotlienc=1.1.0=hb9d3cd8_3
  - libcblas=3.9.0=26_linux64_mkl
  - libclang-cpp20.1=20.1.7=default_h1df26ce_0
  - libclang13=20.1.7=default_he06ed0a_0
  - libcups=2.3.3=hb8b1518_5
  - libcurl=8.13.0=h332b0f4_0
  - libdeflate=1.24=h86f0d12_0
  - libdrm=2.4.125=hb9d3cd8_0
  - libedit=3.1.20230828=h5eee18b_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=h7f8727e_1
  - libexpat=2.7.0=h5888daf_0
  - libffi=3.4.6=h2dba641_1
  - libfreetype=2.13.3=ha770c72_1
  - libfreetype6=2.13.3=h48d6fc4_1
  - libgcc=14.2.0=h767d61c_2
  - libgcc-ng=14.2.0=h69a702a_2
  - libgfortran=14.2.0=h69a702a_2
  - libgfortran5=14.2.0=hf1ad2bd_2
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.84.2=h3618099_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libiconv=1.18=h4ce23a2_1
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - liblapack=3.9.0=26_linux64_mkl
  - libllvm20=20.1.7=he9d0ab4_0
  - liblzma=5.8.1=hb9d3cd8_0
  - libmpdec=4.0.0=h5eee18b_0
  - libnetcdf=4.9.2=nompi_h80fb2b6_111
  - libnghttp2=1.64.0=h161d5f1_0
  - libntlm=1.8=hb9d3cd8_0
  - libopengl=1.7.0=ha4b6fd6_2
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.49=h943b412_0
  - libpq=17.5=h27ae623_0
  - libsqlite=3.50.1=hee588c1_0
  - libssh2=1.11.1=hf672d98_0
  - libstdcxx=14.2.0=h8f9b012_2
  - libstdcxx-ng=14.2.0=h4852527_2
  - libtiff=4.7.0=hf01ce69_5
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.17.0=h8a09558_0
  - libxkbcommon=1.10.0=h65c71a3_0
  - libxml2=2.13.8=h4bc477f_0
  - libxslt=1.1.39=h76b75d6_0
  - libzip=1.11.2=h6991a6a_0
  - libzlib=1.3.1=hb9d3cd8_2
  - llvm-openmp=20.1.2=h024ca30_0
  - lz4-c=1.9.4=h6a678d5_1
  - matplotlib=3.10.3=py313h78bf25f_0
  - matplotlib-base=3.10.3=py313h129903b_0
  - mkl=2023.2.0=h84fe81f_50496
  - mkl-service=2.4.0=py313h5eee18b_2
  - mkl_fft=1.3.11=py313h5eee18b_0
  - mkl_random=1.2.8=py313h06d7b56_0
  - mplcursors=0.6=pyhd8ed1ab_1
  - munkres=1.1.4=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - netcdf4=1.7.2=nompi_py313h2a70696_101
  - numexpr=2.10.1=py313h3c60e43_0
  - numpy=2.2.4=py313hf4aebb8_0
  - numpy-base=2.2.4=py313h3fc9231_0
  - openjpeg=2.5.3=h5fbd93e_0
  - openldap=2.6.10=he970967_0
  - openssl=3.5.0=h7b32b05_1
  - packaging=24.2=py313h06a4308_0
  - pandas=2.2.3=py313h6a678d5_0
  - patsy=1.0.1=py313h06a4308_0
  - pcre2=10.45=hc749103_0
  - pillow=11.2.1=py313h8db990d_0
  - pip=25.0=py313h06a4308_0
  - pixman=0.46.2=h29eaf8c_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pyparsing=3.2.3=pyhd8ed1ab_1
  - pyside6=6.9.1=py313h7dabd7a_0
  - python=3.13.2=hf636f53_101_cp313
  - python-dateutil=2.9.0post0=py313h06a4308_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.13=0_cp313
  - qhull=2020.2=h434a139_5
  - qt6-main=6.9.1=h0384650_0
  - readline=8.2=h5eee18b_0
  - scikit-learn=1.7.0=py313h8ef605b_1
  - scipy=1.15.2=py313h86fcf2b_0
  - setuptools=72.1.0=py313h06a4308_0
  - six=1.17.0=py313h06a4308_0
  - snappy=1.2.1=h6a678d5_0
  - statsmodels=0.14.4=py313ha014f3b_0
  - tbb=2021.8.0=hdb19cb5_0
  - threadpoolctl=3.5.0=py313h7040dfc_0
  - tk=8.6.13=noxft_h4845f30_101
  - tornado=6.5.1=py313h536fd9c_0
  - tzdata=2025a=h04d1e81_0
  - wayland=1.23.1=h3e06ad9_1
  - wheel=0.45.1=py313h06a4308_0
  - xcb-util=0.4.1=hb711507_2
  - xcb-util-cursor=0.1.5=hb9d3cd8_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.45=hb9d3cd8_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
    - attrs==25.3.0
    - fastjsonschema==2.21.1
    - gsw==3.6.19
    - jsonschema==4.24.0
    - jsonschema-specifications==2025.4.1
    - jupyter-core==5.8.1
    - nbformat==5.10.4
    - nbstripout==0.8.1
    - platformdirs==4.3.8
    - pytz==2025.2
    - referencing==0.36.2
    - rpds-py==0.26.0
    - traitlets==5.14.3
    - xarray==2025.3.1
prefix: /users/jnickla1/.conda/envs/cleanpy
